### ISSUE TITLE
Not compatible with locust 0.13

### ISSUE THREAD

**Issue by lagarino** [myzhan/locust4j#11]
Locust 0.13 was released on the 14th of November 2019. When trying to run a locust4j slave with a dockerized master on version 0.13, the master throws:

``` python
[2019-11-18 12:04:38,469] perf-test-ui-6744849bb7jw9ww/ERROR/stderr: Traceback (most recent call last):
[2019-11-18 12:04:38,482] perf-test-ui-6744849bb7jw9ww/ERROR/stderr:
[2019-11-18 12:04:38,483] perf-test-ui-6744849bb7jw9ww/ERROR/stderr: File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
[2019-11-18 12:04:38,483] perf-test-ui-6744849bb7jw9ww/ERROR/stderr:
[2019-11-18 12:04:38,483] perf-test-ui-6744849bb7jw9ww/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/locust/runners.py", line 382, in client_listener
    events.slave_report.fire(client_id=msg.node_id, data=msg.data)
[2019-11-18 12:04:38,483] perf-test-ui-6744849bb7jw9ww/ERROR/stderr:
[2019-11-18 12:04:38,483] perf-test-ui-6744849bb7jw9ww/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/locust/events.py", line 34, in fire
    handler(**kwargs)
[2019-11-18 12:04:38,483] perf-test-ui-6744849bb7jw9ww/ERROR/stderr:
[2019-11-18 12:04:38,483] perf-test-ui-6744849bb7jw9ww/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/locust/stats.py", line 642, in on_slave_report
    global_stats.total.extend(StatsEntry.unserialize(data["stats_total"]))
[2019-11-18 12:04:38,483] perf-test-ui-6744849bb7jw9ww/ERROR/stderr:
[2019-11-18 12:04:38,484] perf-test-ui-6744849bb7jw9ww/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/locust/stats.py", line 428, in unserialize
    setattr(obj, key, data[key])
[2019-11-18 12:04:38,484] perf-test-ui-6744849bb7jw9ww/ERROR/stderr:
[2019-11-18 12:04:38,484] perf-test-ui-6744849bb7jw9ww/ERROR/stderr: KeyError: 'num_fail_per_sec'
[2019-11-18 12:04:38,484] perf-test-ui-6744849bb7jw9ww/ERROR/stderr:
[2019-11-18 12:04:38,484] perf-test-ui-6744849bb7jw9ww/ERROR/stderr: 2019-11-18T12:04:38Z
[2019-11-18 12:04:38,484] perf-test-ui-6744849bb7jw9ww/ERROR/stderr:
[2019-11-18 12:04:38,484] perf-test-ui-6744849bb7jw9ww/ERROR/stderr: <Greenlet at 0x7f425c7b8e48: <bound method MasterLocustRunner.client_listener of <locust.runners.MasterLocustRunner object at 0x7f425d525400>>> failed with KeyError
```
I suspect it's related to the new information being reported:
https://github.com/locustio/locust/pull/1125
https://github.com/locustio/locust/pull/945

**Comment by lagarino** [comment]
Fixed on https://github.com/myzhan/locust4j/pull/12

**Comment by lagarino** [comment]
@myzhan Any possibility of releasing a new version now that this has been fixed?

**Comment by myzhan** [comment]
OK, I'm pushing 1.0.8 to the maven central
