### ISSUE TITLE
Locust4j Slave fails to send heartbeat to master

### ISSUE THREAD

**Issue by ArunaGit2020** [myzhan/locust4j#15]
Hi,
Thanks for nice useful library!

OS: MacOS-Mojave, Openstack - CentOS7
Java: OpenJDK11, OpenJDK8

I am trying to run Locust4j as per this link using Java : https://www.blazemeter.com/blog/locust-performance-testing-using-java-and-kotlin/

Once I run the main class, I see this log statement in master log:
INFO/locust.runners: Client '' reported as ready. Currently 1 clients ready to swarm.

And, java main class log says: 
DEBUG com.github.myzhan.locust4j.rpc.ZeromqClient  - Locust4j is connected to master(127.0.0.1:5557)

However, immediately within second, I keep getting this error in master log :

2020-02-24 04:58:26,104] dca90482df05/ERROR/stderr: Traceback (most recent call last):
[2020-02-24 04:58:26,105] dca90482df05/ERROR/stderr: 
[2020-02-24 04:58:26,105] dca90482df05/ERROR/stderr: File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
[2020-02-24 04:58:26,105] dca90482df05/ERROR/stderr: 
[2020-02-24 04:58:26,105] dca90482df05/ERROR/stderr: File "/usr/local/lib/python3.7/site-packages/locust/runners.py", line 462, in client_listener
    c.cpu_usage = msg.data['current_cpu_usage']
[2020-02-24 04:58:26,105] dca90482df05/ERROR/stderr: 
[2020-02-24 04:58:26,105] dca90482df05/ERROR/stderr: KeyError: 'current_cpu_usage'
[2020-02-24 04:58:26,105] dca90482df05/ERROR/stderr: 
[2020-02-24 04:58:26,106] dca90482df05/ERROR/stderr: 2020-02-24T10:58:26Z
[2020-02-24 04:58:26,106] dca90482df05/ERROR/stderr: 
[2020-02-24 04:58:26,106] dca90482df05/ERROR/stderr: <Greenlet at 0x10a16f050: <bound method MasterLocustRunner.client_listener of <locust.runners.MasterLocustRunner object at 0x10a164790>>> failed with KeyError
[2020-02-24 04:58:30,436] dca90482df05/INFO/locust.runners: Slave dca90482df05_2513ac6bee7e675ef4cf877736e3da33 failed to send heartbeat, setting state to missing.
 
I tried with JDK11, JDK8 and in Mac & Openstack as well. Also, tried running it from Eclipse IDE and through terminal as mentioned in the above BlazeMeter url. No luck. What might be going wrong? 

Thanks!

**Comment by ArunaGit2020** [comment]
I see there is a PR: https://github.com/myzhan/locust4j/pull/14 open to address this "current_cpu_usage" . So, I am closing this issue assuming that would be merged soon.

**Comment by myzhan** [comment]
Yes, 1.0.9 has been released. It may take a while to sync to the maven central.

**Comment by ArunaGit2020** [comment]
Thank you! I can see that reflected in maven.
